#+TITLE: Andre's Emacs configuration

* Configuration
** About
This file was created using [[http://orgmode.org/worg/org-contrib/babel/][org-babel]] mode.
It is an example of literate programming.

Inspired by [[http://pages.sachachua.com/.emacs.d/Sacha.html][Sacha's Emacs configuration]].

** Initialisation
#+BEGIN_SRC emacs-lisp
(require 'package)
(add-to-list 'package-archives
             '("melpa" . "http://melpa.org/packages/") t)
(package-initialize)
#+END_SRC

** General
*** Relative numbers
From http://juanjoalvarez.net/es/detail/2014/sep/19/vim-emacsevil-chaotic-migration-guide/
#+BEGIN_SRC emacs-lisp
(add-hook 'org-mode-hook 'relative-line-numbers-mode t)
(add-hook 'org-mode-hook 'line-number-mode t)
(add-hook 'org-mode-hook 'column-number-mode t)
#+END_SRC

#+BEGIN_SRC emacs-lisp
(add-hook 'prog-mode-hook 'relative-line-numbers-mode t)
(add-hook 'prog-mode-hook 'line-number-mode t)
(add-hook 'prog-mode-hook 'column-number-mode t)
#+END_SRC
   
*** Move between windows
Use super + arrow keys to move between Emacs windows.

#+BEGIN_SRC emacs-lisp
(when (fboundp 'windmove-default-keybindings)
  (windmove-default-keybindings 'super))
#+END_SRC

*** Change "yes or no" to "y or n"
From http://pages.sachachua.com/.emacs.d/Sacha.html
#+BEGIN_SRC emacs-lisp
(fset 'yes-or-no-p 'y-or-n-p)
#+END_SRC

*** Bell
Use visual alarm instead of sound.
#+BEGIN_SRC emacs-lisp
(setq visible-bell 1)
#+END_SRC

*** Backups
From http://pages.sachachua.com/.emacs.d/Sacha.html#unnumbered-1
#+BEGIN_SRC emacs-lisp
(setq backup-directory-alist '(("." . "~/.emacs.d/backups")))
(setq delete-old-versions -1)    ; do not delete old versions
(setq version-control t)         ; backups are numbered
(setq vc-make-backup-files t)    ; by default, emacs does not backup files managed by a version control system. Setting it to "t" modifies that.
(setq auto-save-file-name-transforms '((".*" "~/.emacs.d/auto-save-list/" t)))
#+END_SRC
*** Get system's environment variables
[[https://github.com/purcell/exec-path-from-shell][Purcell's package]] =exec-path-from-shell= makes this easy on OS X.
#+BEGIN_SRC emacs-lisp
(when (memq window-system '(mac ns))
  (exec-path-from-shell-initialize))
#+END_SRC

*** Semantic
    Quoting to the Emacs manual, "Semantic is a package that provides language-aware editing commands based on source code parsers."
It is used by =helm-semantic-or-imenu=.
#+BEGIN_SRC emacs-lisp
(semantic-mode 1)
#+END_SRC
** Evil
*** evil-leader
Use space as the leader key.
Required before =evil-mode= is enabled.

#+BEGIN_SRC emacs-lisp
(global-evil-leader-mode)
; enable C-<leader> when not in normal mode
(setq evil-leader/in-all-states 1)
(evil-leader/set-leader "<SPC>")
(evil-leader/set-key
  "f" 'helm-M-x
  "h" 'help-command
  "b" 'helm-mini
  "k" 'kill-this-buffer
  "l" 'helm-locate
  "i" 'helm-semantic-or-imenu
  "o" 'other-window
  "q" 'save-buffers-kill-terminal
  "E" 'go-errcheck
  "w" 'save-buffer
  "W" 'save-some-buffers
  "z" 'suspend-emacs
  "<SPC>" 'evilnc-comment-or-uncomment-lines
  ; evil-nerd-commenter
  "ci" 'evilnc-comment-or-uncomment-lines
  "cl" 'evilnc-quick-comment-or-uncomment-to-the-line
  "cc" 'evilnc-copy-and-comment-lines
  "cp" 'evilnc-comment-or-uncomment-paragraphs
  "cr" 'comment-or-uncomment-region
  "cv" 'evilnc-toggle-invert-comment-line-by-line
  " "  'evilnc-comment-operator ; Use <SPC> instead of \\
  )
#+END_SRC

*** Org-mode keybindings
Based on https://github.com/edwtjo/evil-org-mode.
#+BEGIN_SRC emacs-lisp
(evil-define-key 'normal org-mode-map
  "<" 'org-metaleft
  ">" 'org-metaright
  "gh" 'outline-up-heading
  "gl" 'outline-next-visible-heading
  "gj" 'org-forward-heading-same-level
  "gk" 'org-backward-heading-same-level
  (kbd "TAB") 'org-cycle ; overwrites evil C-i in terminal
  )
#+END_SRC

#+BEGIN_SRC emacs-lisp
(evil-leader/set-key-for-mode 'org-mode
  "ml" 'org-insert-link
  "mL" 'org-store-link
  "i" 'helm-org-in-buffer-headings
)
#+END_SRC

*** Enable evil-mode
#+BEGIN_SRC emacs-lisp
(evil-mode 1)
#+END_SRC

*** Make esc like C-g
From https://github.com/davvil/.emacs.d/blob/master/init.el
#+BEGIN_SRC emacs-lisp
(defun minibuffer-keyboard-quit ()
  "Abort recursive edit.
In Delete Selection mode, if the mark is active, just deactivate it;
then it takes a second \\[keyboard-quit] to abort the minibuffer."
  (interactive)
  (if (and delete-selection-mode transient-mark-mode mark-active)
      (setq deactivate-mark  t)
    (when (get-buffer "*Completions*") (delete-windows-on "*Completions*"))
    (abort-recursive-edit)))
(define-key evil-normal-state-map [escape] 'keyboard-quit)
(define-key evil-visual-state-map [escape] 'keyboard-quit)
(define-key minibuffer-local-map [escape] 'minibuffer-keyboard-quit)
(define-key minibuffer-local-ns-map [escape] 'minibuffer-keyboard-quit)
(define-key minibuffer-local-completion-map [escape] 'minibuffer-keyboard-quit)
(define-key minibuffer-local-must-match-map [escape] 'minibuffer-keyboard-quit)
(define-key minibuffer-local-isearch-map [escape] 'minibuffer-keyboard-quit)
(global-set-key [escape] 'evil-exit-emacs-state)
#+END_SRC

*** Evil related packages
**** evil-numbers
#+BEGIN_SRC emacs-lisp
(require 'evil-numbers)
#+END_SRC

**** evil-surround
#+BEGIN_SRC emacs-lisp
(require 'evil-surround)
(global-evil-surround-mode 1)
#+END_SRC

**** evil-visualstar
#+BEGIN_SRC emacs-lisp
(global-evil-visualstar-mode)
#+END_SRC

** Helm
*** Keybindings and initialisation
Some snippets of code were taken from http://tuhdo.github.io/helm-intro.html
#+BEGIN_SRC emacs-lisp
(require 'helm)
(require 'helm-config)
#+END_SRC

#+NAME helm-keybindings
| Key     | Command                        | Description                         |
|---------+--------------------------------+-------------------------------------|
| TAB     | helm-execute-persistent-action | Perform action without exiting helm |
| C-z     | helm-select-action             | List actions for current item       |
| C-c h o | helm-occur                     | Replace default =occur=             |
| C-c h g | helm-google-suggest            | Open Google search for given string |
| C-x b   | helm-mini                      | List buffers and recentf            |
| M-x     | helm-M-x                       | Replace default M-x                 |

#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-c h") 'helm-command-prefix)
(global-unset-key (kbd "C-x c"))
(global-set-key (kbd "C-c h o") 'helm-occur)
(global-set-key (kbd "C-c h g") 'helm-google-suggest)

(global-set-key (kbd "M-x") 'helm-M-x)
(setq helm-M-x-fuzzy-match t) ;; fuzzy matching for helm-M-x

(global-set-key (kbd "C-x b") 'helm-mini)
(setq helm-buffers-fuzzy-matching t
      helm-recentf-fuzzy-match    t)

(setq helm-semantic-fuzzy-match t
      helm-imenu-fuzzy-match    t)

(define-key helm-map (kbd "<tab>") 'helm-execute-persistent-action)
(define-key helm-map (kbd "C-i") 'helm-execute-persistent-action) ; make TAB work in terminal
(define-key helm-map (kbd "C-z") 'helm-select-action) ; list actions using C-z

(helm-mode 1)
#+END_SRC

*** helm-locate
Adjust the command equivalent to =locate= command depending on the operational system.
From https://github.com/xiaohanyu/oh-my-emacs/commit/34bf80a0fea61ff1112accfb8448a45dafd2204a
#+BEGIN_SRC emacs-lisp
(require 'cl) ; otherwise emacs complains about "case" in the following block
(setq helm-locate-command
      (case system-type
            ('gnu/linux "locate -i -r %s")
            ('berkeley-unix "locate -i %s")
            ('windows-nt "es %s")
            ('darwin "mdfind -name %s %s")
            (t "locate %s")))
#+END_SRC

*** helm-descbinds
Alternative to default describe-bindings
#+BEGIN_SRC emacs-lisp
(require 'helm-descbinds)
(helm-descbinds-mode)
#+END_SRC
** Customise interface
*** custom-set-variables
#+BEGIN_SRC emacs-lisp
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.

 ; consider all themes as safe
 '(custom-safe-themes t)
 ; start maximized
 '(initial-frame-alist (quote ((fullscreen . maximized)))))
#+END_SRC

*** custom-set-faces
#+BEGIN_SRC emacs-lisp
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :stipple nil :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "nil" :family "Monaco")))))
#+END_SRC

** Org-mode configuration

*** Org-mode global suggested keys
#+BEGIN_SRC emacs-lisp
(global-set-key "\C-cl" 'org-store-link)
(global-set-key "\C-cc" 'org-capture)
(global-set-key "\C-ca" 'org-agenda)
(global-set-key "\C-cb" 'org-iswitchb)
#+END_SRC

*** Timestamps in done tasks
#+BEGIN_SRC emacs-lisp
(setq org-log-done t)
#+END_SRC

*** Remember cursor position
#+BEGIN_SRC emacs-lisp
(setq save-place-file "~/.emacs.d/saveplace")
(setq-default save-place t)
(require 'saveplace)
#+END_SRC

** Theme & visual configuration
*** Disable blinking cursor
    Restore sanity.
#+BEGIN_SRC emacs-lisp
(blink-cursor-mode 0)
#+END_SRC
*** Remove scrollbars, menu bars, and toolbars
#+BEGIN_SRC emacs-lisp
(when (fboundp 'menu-bar-mode) (menu-bar-mode -1))
(when (fboundp 'tool-bar-mode) (tool-bar-mode -1))
(when (fboundp 'scroll-bar-mode) (scroll-bar-mode -1))
#+END_SRC

*** Theme
#+BEGIN_SRC emacs-lisp
(if window-system
    ;; (load-theme 'sanityinc-solarized-light t)
    (load-theme 'zenburn t)
  (load-theme 'wombat t))
#+END_SRC

*** Disable current theme before loading new one
From http://stackoverflow.com/a/15595000
#+BEGIN_SRC emacs-lisp
(defadvice load-theme 
  (before theme-dont-propagate activate)
  (mapcar #'disable-theme custom-enabled-themes))
#+END_SRC

*** Do not show splash screen
#+BEGIN_SRC emacs-lisp
(setq inhibit-startup-message t)
#+END_SRC

** Other packages 
*** Company-mode
Use company-mode in all buffers
#+BEGIN_SRC emacs-lisp
(add-hook 'after-init-hook 'global-company-mode)
(setq company-idle-delay 0)
#+END_SRC

*** Ibuffer
**** Initialisation
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-x C-b") 'ibuffer)
#+END_SRC

**** Keybindings
     Differences with the default configuration:
| Key | Function |
|-----+----------|
|     |          |
      ;(kbd "J") 'ibuffer-jump-to-buffer
      ;(kbd "j") 'evil-next-line    
      ;(kbd "k") 'evil-previous-line
      ;<SPC> forward-line remove
      ;ibuffer-do-kill-lines from k to K
#+BEGIN_SRC emacs-lisp
(eval-after-load 'ibuffer
  '(progn
     (evil-set-initial-state 'ibuffer-mode 'normal)
     (evil-define-key 'normal ibuffer-mode-map
;       (kbd "m") 'ibuffer-mark-forward
;       (kbd "t") 'ibuffer-toggle-marks
;       (kbd "u") 'ibuffer-unmark-forward
;       (kbd "=") 'ibuffer-diff-with-file
       (kbd "J") 'ibuffer-jump-to-buffer
       (kbd "j") 'evil-next-line
;       (kbd "M-g") 'ibuffer-jump-to-buffer
;       (kbd "M-s a C-s") 'ibuffer-do-isearch
;       (kbd "M-s a M-C-s") 'ibuffer-do-isearch-regexp
;       (kbd "M-s a C-o") 'ibuffer-do-occur
;       (kbd "DEL") 'ibuffer-unmark-backward
;       (kbd "M-DEL") 'ibuffer-unmark-all
;       (kbd "* *") 'ibuffer-unmark-all
;       (kbd "* M") 'ibuffer-mark-by-mode
;       (kbd "* m") 'ibuffer-mark-modified-buffers
;       (kbd "* u") 'ibuffer-mark-unsaved-buffers
;       (kbd "* s") 'ibuffer-mark-special-buffers
;       (kbd "* r") 'ibuffer-mark-read-only-buffers
;       (kbd "* /") 'ibuffer-mark-dired-buffers
;       (kbd "* e") 'ibuffer-mark-dissociated-buffers
;       (kbd "* h") 'ibuffer-mark-help-buffers
;       (kbd "* z") 'ibuffer-mark-compressed-file-buffers
;       (kbd ".") 'ibuffer-mark-old-buffers
;    
;       (kbd "d") 'ibuffer-mark-for-delete
;       (kbd "C-d") 'ibuffer-mark-for-delete-backwards
;       (kbd "k") 'ibuffer-mark-for-delete
;       (kbd "x") 'ibuffer-do-kill-on-deletion-marks
;    
;       ;; immediate operations
;       (kbd "n") 'ibuffer-forward-line
;       ; (kbd "SPC") 'forward-line
;       (kbd "p") 'ibuffer-backward-line
;       (kbd "M-}") 'ibuffer-forward-next-marked
;       (kbd "M-{") 'ibuffer-backwards-next-marked
;       (kbd "l") 'ibuffer-redisplay
;       (kbd "g") 'ibuffer-update
;       (kbd "`") 'ibuffer-switch-format
;       (kbd "-") 'ibuffer-add-to-tmp-hide
;       (kbd "+") 'ibuffer-add-to-tmp-show
;       (kbd "b") 'ibuffer-bury-buffer
;       (kbd ",") 'ibuffer-toggle-sorting-mode
;       (kbd "s i") 'ibuffer-invert-sorting
;       (kbd "s a") 'ibuffer-do-sort-by-alphabetic
;       (kbd "s v") 'ibuffer-do-sort-by-recency
;       (kbd "s s") 'ibuffer-do-sort-by-size
;       (kbd "s f") 'ibuffer-do-sort-by-filename/process
;       (kbd "s m") 'ibuffer-do-sort-by-major-mode
;    
;       (kbd "/ m") 'ibuffer-filter-by-used-mode
;       (kbd "/ M") 'ibuffer-filter-by-derived-mode
;       (kbd "/ n") 'ibuffer-filter-by-name
;       (kbd "/ c") 'ibuffer-filter-by-content
;       (kbd "/ e") 'ibuffer-filter-by-predicate
;       (kbd "/ f") 'ibuffer-filter-by-filename
;       (kbd "/ >") 'ibuffer-filter-by-size-gt
;       (kbd "/ <") 'ibuffer-filter-by-size-lt
;       (kbd "/ r") 'ibuffer-switch-to-saved-filters
;       (kbd "/ a") 'ibuffer-add-saved-filters
;       (kbd "/ x") 'ibuffer-delete-saved-filters
;       (kbd "/ d") 'ibuffer-decompose-filter
;       (kbd "/ s") 'ibuffer-save-filters
;       (kbd "/ p") 'ibuffer-pop-filter
;       (kbd "/ !") 'ibuffer-negate-filter
;       (kbd "/ t") 'ibuffer-exchange-filters
;       (kbd "/ TAB") 'ibuffer-exchange-filters
;       (kbd "/ o") 'ibuffer-or-filter
;       (kbd "/ g") 'ibuffer-filters-to-filter-group
;       (kbd "/ P") 'ibuffer-pop-filter-group
;       (kbd "/ D") 'ibuffer-decompose-filter-group
;       (kbd "/ /") 'ibuffer-filter-disable
;    
;       (kbd "M-n") 'ibuffer-forward-filter-group
;       (kbd "\t") 'ibuffer-forward-filter-group
;       (kbd "M-p") 'ibuffer-backward-filter-group
;       (kbd "<backtab>") 'ibuffer-backward-filter-group
;       (kbd "M-j") 'ibuffer-jump-to-filter-group
;       (kbd "C-k") 'ibuffer-kill-line
;       (kbd "C-y") 'ibuffer-yank
;       (kbd "/ S") 'ibuffer-save-filter-groups
;       (kbd "/ R") 'ibuffer-switch-to-saved-filter-groups
;       (kbd "/ X") 'ibuffer-delete-saved-filter-groups
;       (kbd "/ \\") 'ibuffer-clear-filter-groups
;    
;       (kbd "q") 'ibuffer-quit
;       (kbd "h") 'describe-mode
;       (kbd "?") 'describe-mode
;    
;       (kbd "% n") 'ibuffer-mark-by-name-regexp
;       (kbd "% m") 'ibuffer-mark-by-mode-regexp
;       (kbd "% f") 'ibuffer-mark-by-file-name-regexp
;    
;       (kbd "C-t") 'ibuffer-visit-tags-table
;    
;       (kbd "|") 'ibuffer-do-shell-command-pipe
;       (kbd "!") 'ibuffer-do-shell-command-file
;       (kbd "~") 'ibuffer-do-toggle-modified
;       ;; marked operations
;       (kbd "A") 'ibuffer-do-view
;       (kbd "D") 'ibuffer-do-delete
;       (kbd "E") 'ibuffer-do-eval
;       (kbd "F") 'ibuffer-do-shell-command-file
;       (kbd "I") 'ibuffer-do-query-replace-regexp
;       (kbd "H") 'ibuffer-do-view-other-frame
;       (kbd "N") 'ibuffer-do-shell-command-pipe-replace
;       (kbd "M") 'ibuffer-do-toggle-modified
;       (kbd "O") 'ibuffer-do-occur
;       (kbd "P") 'ibuffer-do-print
;       (kbd "Q") 'ibuffer-do-query-replace
;       (kbd "R") 'ibuffer-do-rename-uniquely
;       (kbd "S") 'ibuffer-do-save
;       (kbd "T") 'ibuffer-do-toggle-read-only
;       (kbd "U") 'ibuffer-do-replace-regexp
;       (kbd "V") 'ibuffer-do-revert
;       (kbd "W") 'ibuffer-do-view-and-eval
;       (kbd "X") 'ibuffer-do-shell-command-pipe
;    
       (kbd "k") 'evil-previous-line
       (kbd "K") 'ibuffer-do-kill-lines
;       (kbd "w") 'ibuffer-copy-filename-as-kill
;    
;       (kbd "RET") 'ibuffer-visit-buffer
;       (kbd "e") 'ibuffer-visit-buffer
;       (kbd "f") 'ibuffer-visit-buffer
;       (kbd "C-x C-f") 'ibuffer-find-file
;       (kbd "o") 'ibuffer-visit-buffer-other-window
;       (kbd "C-o") 'ibuffer-visit-buffer-other-window-noselect
;       (kbd "M-o") 'ibuffer-visit-buffer-1-window
;       (kbd "v") 'ibuffer-do-view
;       (kbd "C-x v") 'ibuffer-do-view-horizontally
;       (kbd "C-c C-a") 'ibuffer-auto-mode
;       (kbd "C-x 4 RET") 'ibuffer-visit-buffer-other-window
;       (kbd "C-x 5 RET") 'ibuffer-visit-buffer-other-frame
       )
    )
)  
#+END_SRC
*** Smartparens
#+BEGIN_SRC emacs-lisp
(smartparens-global-mode t)
(require 'smartparens-config)
#+END_SRC

*** Yasnippet
#+BEGIN_SRC emacs-lisp
(require 'yasnippet)
(yas-reload-all) ; global-mode can affect negatively other modes, use this instead to used it as a non-global minor mode
(add-hook 'prog-mode-hook
          '(lambda ()
             (yas-minor-mode)))
#+END_SRC
*** Flycheck
#+BEGIN_SRC emacs-lisp
(add-hook 'after-init-hook #'global-flycheck-mode)
#+END_SRC

*** Slime
From http://nathantypanski.com/blog/2014-08-03-a-vim-like-emacs-config.html
#+BEGIN_SRC emacs-lisp
(require 'elisp-slime-nav)

(defun my-lisp-hook ()
  (elisp-slime-nav-mode)
  (turn-on-eldoc-mode)
  )

(add-hook 'emacs-lisp-mode-hook 'my-lisp-hook)
#+END_SRC
*** Mardown-mode
**** Initialisation
Use Github flavored markdown.
#+BEGIN_SRC emacs-lisp
(autoload 'markdown-mode "markdown-mode"
   "Major mode for editing Markdown files" t)
(add-to-list 'auto-mode-alist '("\\.markdown\\'" . gfm-mode))
(add-to-list 'auto-mode-alist '("\\.md\\'" . gfm-mode))
#+END_SRC
**** Keybindings
#+BEGIN_SRC 
(evil-leader/set-key-for-mode 'gfm-mode
  "ml" 'markdown-insert-link
)
#+END_SRC
** Formatting
*** Wrap lines
Use =visual line mode= globally.
#+BEGIN_SRC emacs-lisp
;; (add-hook 'text-mode-hook 'turn-on-visual-line-mode)
(global-visual-line-mode 1)
#+END_SRC

*** Identation
Use spaces instead of tabs.
#+BEGIN_SRC emacs-lisp
(setq-default tab-width 4 indent-tabs-mode nil)
(setq-default c-basic-offset 4 c-default-style "bsd")
#+END_SRC
