#!/usr/bin/env bash
# Several settings were taken from https://github.com/mathiasbynens/dotfiles/blob/master/.osx

# "Disable" blinking cursor
defaults write -g NSTextInsertionPointBlinkPeriodOn -float 999999999999

# Disable the sound effects on boot
sudo nvram SystemAudioVolume=" "

